[Feature #103] Tabular module - change method responsibility
kbss-cvut/s-pipes pull request #105
Opened 2022-09-13 07:24 UTC by Matthew-Kulich

2022-09-13 11:44 UTC, blcham requested changes
see my comments

2022-09-13 11:44 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/Column.java
> +    public void setProperty(String dataPrefix, StreamResource sourceResource) throws UnsupportedEncodingException {
Agreed, we do not want to depend on StreamResource ... I would put url.

2022-09-13 11:44 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/Column.java
> +    private String getPropertyUrl(String dataPrefix, StreamResource sourceResource)
same as above.

2022-09-13 11:44 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/Column.java
> +                outputModel.add(ResourceFactory.createStatement(
this is very strange ... why column modifies output model ?

2022-09-13 11:44 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/TableSchema.java
> +
same as above.

2022-09-13 11:44 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/Column.java
> +                outputModel.add(ResourceFactory.createStatement(
- issues of the function:
  - it is not very clear what method does -- it does at least 2 things
  - it modifies outputModel which is outside of the column ... so multiple objects modifies output model which might be quite dangerous ... you might not be able to track easily when outputModel was modified during the transformation -- this should be quite clear not spread in different objects 
   - not sure if  "createAboutUrl(tableSchemaAboutUrl, rowNumber)" is not responsibility of tableSchema (maybe it is all right ... just consider it)

2022-09-13 11:44 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/Column.java
> +                outputModel.add(ResourceFactory.createStatement(
btw. i stopped seeing references to the specification (i hope we did not loose it :) :) :)

2022-09-13 12:46 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/Column.java
> +                outputModel.add(ResourceFactory.createStatement(
We didn't lose it :)) It is still there.

2022-09-14 07:35 UTC, blcham approved these changes

2022-09-14 07:39 UTC, merged