Make TableSchema errors more understandable + add diff
kbss-cvut/s-pipes pull request #121
Opened 2022-10-07 11:11 UTC by Matthew-Kulich

2022-10-07 20:50 UTC, blcham requested changes
see my comments

2022-10-07 20:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                "\\n").build();
Will this work on windows?

2022-10-07 20:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                        hasInputSchema ? tableSchema.getColumn(columnName) : null);
```suggestion
                schemaColumn.setProperty(
                        dataPrefix, 
                        sourceResource.getUri(),
                        hasInputSchema ? tableSchema.getColumn(columnName) : null
                 );
```

2022-10-07 20:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                        hasInputSchema ? tableSchema.getColumn(columnName) : null);
You use many formatting styles of function calls with multiple parameters if it does not fit the line. How about choosing one? I like it as it makes it very easy to understand where a function call starts and what are the params. But if you mix styles it is hard to read. I suggest doing the following for multiline function call:
- first param should be on new line
- never put two parameters on the same line 
- always  finish with closing parenthesis that is in the separate line

2022-10-07 20:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                "\\n").build();
Shouldn't we use rather System.lineSeparator() ?

2022-10-07 20:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/TableSchema.java
> +    private StringBuilder throwColumnsError(List<Column> outputColumns, List<Column> columnsList, String message) {
why do you call it throwColumnsError if you don't throw anything here? Is it rather something like getColumnsError?

2022-10-07 20:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/TableSchema.java
> +    private String addSchemaDiff() {
why this method is called add if it does not add anything to anything ... it just get some message so why not call it getSchemaDiff?

2022-10-09 17:14 UTC, merged

2022-10-09 17:14 UTC, blcham commented
@Matthew-Kulich I am merging this pull request as I am experiencing issues with the tabular module. I hope it brings me better logging if nothing.

2022-10-12 08:26 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/TableSchema.java
> +    private String addSchemaDiff() {
You're right. Forgot to change it after refactoring. 

Done & already merged.

2022-10-12 08:26 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/model/TableSchema.java
> +    private StringBuilder throwColumnsError(List<Column> outputColumns, List<Column> columnsList, String message) {
Yeah

Done & already merged.

2022-10-12 08:29 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                        hasInputSchema ? tableSchema.getColumn(columnName) : null);
Ok.

Done but not merged yet. (I will create a pull request for that because I merged it (https://github.com/kbss-cvut/s-pipes/pull/124) and then did notice the comment in the issue)

2022-10-12 08:31 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                "\\n").build();
I'm not sure, but I agree