[New] Add custom tokenizer for csv processing
kbss-cvut/s-pipes pull request #132
Opened 2022-11-14 09:43 UTC by Matthew-Kulich

2022-11-15 06:15 UTC, blcham requested changes
see my suggestions

2022-11-15 06:15 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/CustomTokenizer.java
> +public class CustomTokenizer extends Tokenizer {
Put also links to both standards:
- TSV
- CSV

inside of the java source code so we know exactly what we were trying to be compliant with.

2022-11-15 06:15 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            ICsvListReader listReader;
We need to throw error if customTokenizer with no quote-ing right?

2022-11-15 10:00 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            ICsvListReader listReader;
Atm, we set the default value to `'\''` if the quote char is not provided. But we can change it the way you suggest

2022-11-15 11:24 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            ICsvListReader listReader;
I thought that if there is no quoting it means no quoting right ?

Is it not compliant with specifications to have no quoting?

2022-11-15 11:29 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            ICsvListReader listReader;
Yeah, you're right, so I will change the implementation a little bit.
It is compliant.

2022-11-15 11:29 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            ICsvListReader listReader;
I mean do  list reader have also default value of quoting when you do this? :
`ICsvListReader listReader = new CsvListReader(getReader(), csvPreference);`

2022-11-15 20:46 UTC, blcham requested changes

2022-11-15 20:46 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    private final Property P_CUSTOM_TOKENIZER = getSpecificParameter("accept-invalid-quoting");
```suggestion
    private final Property P_ACCEPT_INVALID_QUOTING = getSpecificParameter("accept-invalid-quoting");
```

2022-11-15 20:46 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +        acceptInvalidQuoting = getPropertyValue(P_CUSTOM_TOKENIZER, false);
```suggestion
        acceptInvalidQuoting = getPropertyValue(P_ACCEPT_INVALID_QUOTING, false);
```

2022-11-15 20:46 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
>          delimiter = getPropertyValue(P_DELIMITER, '\t');
I suggest using by default CSV, i.e. comma + double-quote + UTF-8.
```
The first set of parameters is there simply do deal with CSV files not compliant with RFC 4180, which specifies a comma as a delimiter, the double-quote as a quote character, and UTF-8 as the encoding.
```

2022-11-15 20:46 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +        quoteCharacter = getPropertyValue(P_QUOTE_CHARACTER, '\0');
In case delimiter is "," or nothing, I would put quoting "\"".

2022-11-16 09:40 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +        quoteCharacter = getPropertyValue(P_QUOTE_CHARACTER, '\0');
Done

2022-11-16 09:40 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
>          delimiter = getPropertyValue(P_DELIMITER, '\t');
Done

2022-11-21 15:07 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/CustomTokenizer.java
> +public class CustomTokenizer extends Tokenizer {
@Matthew-Kulich  I don's see my last comment being addressed.

2022-11-21 15:07 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    private final Property P_CUSTOM_TOKENIZER = getSpecificParameter("use-custom-tokenizer");
I believe this was resolved.

2022-11-21 15:29 UTC, blcham requested changes
See my comment + I believe our implementation is not compliant with TSV specification. 

https://www.iana.org/assignments/media-types/text/tab-separated-values suggest to not having quoting at all and we have quoting '"' by default. Thus, we should behave as follows **by default**:
- for CSV use quoting + UTF-8
- for TSV use no quoting

2022-11-21 21:22 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    private final Property P_CUSTOM_TOKENIZER = getSpecificParameter("use-custom-tokenizer");
Yes

2022-11-21 22:38 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/CustomTokenizer.java
> +public class CustomTokenizer extends Tokenizer {
Yes I saw it and it is nice, but imagine that somebody will want to use tabular module
-- he starts reading the document but there is no reference to default values or bad quoting
-- Thus i suggest to write something like following: 



 * Module for converting tabular data (e.g. CSV or TSV) to RDF.
 * **XXX**
 * <p>
 * The implementation loosely follows the W3C Recommendation described here:
 * <a href="https://www.w3.org/TR/csv2rdf/">Generating RDF from Tabular Data on the Web</a>
 * <p>
 * Within the recommendation, it is possible to define schema


**XXX** - It supports two major processing standards that can be set by separator:
     separator "," -- defaults to CSV standard (http:...), i.e. it uses by default quoting " and UTF-8
     separator "\t" -- defaults to TSV (http:...), with no quoting ....
     other separator -- defaults to ....
In addition it supports bad quoting according to CSV standard, see option "accept-invalid-quoting" and class InvalidQuotingTokenizer

2022-11-22 12:42 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/CustomTokenizer.java
> +public class CustomTokenizer extends Tokenizer {
Alright, I see

2022-11-22 13:27 UTC, blcham requested changes
almost fine, just last issue i believe

2022-11-22 13:27 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +        if(delimiter == ','){
wait, this is another way around. If the user configure module to have:
delimiter == \t
quoteCharacter = " 

we do not want to override it. Moreover, please log that we are using default configuration for CSV / TSV in console if user does not specify it.

2022-11-22 14:06 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +        if(delimiter == ','){
Oh, I see the problem
The last commit should fix this.

2022-11-22 20:37 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            quoteCharacter = '"';
This does not work for specific case:
If user specifies delimiter == ',' it will not set up default quote character to '"'.

2022-11-22 20:37 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            quoteCharacter = '"';
just note, i will fix it in next comment

2022-11-22 20:39 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            ICsvListReader listReader;
I have no answer here but I guess we can resolve this.

2022-11-22 20:43 UTC, blcham approved these changes
LGTM, but see my last commit, please, I cannot put you as a reviewer, unfortunately.

@Matthew-Kulich if it is ok please merge but not forget to change it in scripts (accept-invalid-quoting).

2022-11-22 22:59 UTC, Matthew-Kulich commented
Yeah, LGTM

2022-11-22 22:59 UTC, merged