[New] Add HTML to RDF support
kbss-cvut/s-pipes pull request #138
Opened 2022-12-07 10:25 UTC by Matthew-Kulich

2022-12-10 22:43 UTC, blcham requested changes
not sure if requires changes, please say your opinion on my comment.

2022-12-10 22:43 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            setDelimiter(',');
Tab does not have any meaning in html document, so I suggest to do the following:
- instead of interpreting it as CSV i would interpret it as TSV without quoting (but first you need to replace \t for e.g. two spaces).

Rationale:
- if you use CSV you will have issues with quoting very easily as `<div class="some-style"/>` contain quoting ... 

What do you think about it ?

2023-01-02 10:19 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            setDelimiter(',');
Yeah, TSV makes more sense, so I agree to change it

2023-01-03 08:31 UTC, blcham requested changes
LGTM, just minor addjustments in documentation should be done

2023-01-03 08:31 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/HTML2TSVConvertor.java
> + * This class can be used to read the HTML table from input and convert it to TSV file.
What happens when 2 or 3 tables occurs there?
What happens if \t occurs in the html document, isn't it removed ?

2023-01-03 08:31 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
It  should be said somewhere that it convert to TSV without quoting and that \t is replaced by two spaces ... right ?

2023-01-03 21:45 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/HTML2TSVConvertor.java
> + * This class can be used to read the HTML table from input and convert it to TSV file.
> What happens when 2 or 3 tables occur there?

The algorithm takes and process only the first table. We can log if there are more tables.

> What happens if \t occurs in the html document, isn't it removed ?

It is escaped. For example, if there is `<th>Description\t</th>` in the HTML input, the processed data looks like this
`"Description\\t"`

2023-01-03 21:46 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
Yeah, agree

2023-01-04 05:10 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/HTML2TSVConvertor.java
> + * This class can be used to read the HTML table from input and convert it to TSV file.
hmmm this is statement [1].

2023-01-04 05:10 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
An here you agree that \t is replaced with two spaces. Isn't it in conflict with [1] ?

2023-01-06 09:00 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
Sorry, I got confused right now. Here is an example. If there is an occurrence of exactly "\t", then it is escaped (first example). If there is tab character, it is replaced by two spaced (second example)  
```
<td>123/t</td>      ---> "123\\t"
<td>123     </td>   ---> "123  "
```

2023-01-17 11:25 UTC, blcham requested changes
LGTM, see only minor changes

2023-01-17 11:25 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
I would put it to the sentence at the begining:
Module for converting tabular data (e.g. CSV, TSV, table represented in HTML) to RDF

2023-01-17 11:25 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
```suggestion
 * This module can also be used to process HTML tables, see option
 * {@link TabularModule#processHTMLFile}. First, the HTML table is converted to TSV
```

2023-01-17 11:25 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
This can be resolved.

2023-01-17 11:25 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
```suggestion
 * This module can also be used to process HTML tables. First, the HTML table is converted to TSV while replacing "\t" with two spaces
```

2023-01-18 08:27 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * This module can also be used to process HTML tables. First, the HTML table is converted to TSV
Ok

2023-01-18 09:04 UTC, Matthew-Kulich commented
All changes are done. I can merge, right? @blcham

2023-01-18 15:55 UTC, blcham commented
yes

2023-01-18 19:02 UTC, merged