SPipes debug api
kbss-cvut/s-pipes pull request #149
Opened 2023-02-21 22:54 UTC by mircheqtm

2023-02-23 17:06 UTC, blcham requested changes
I will go over all of it after my comments are resolved.

2023-05-03 14:09 UTC, blcham requested changes
Let's do the review incrementally.

2023-05-03 14:09 UTC, blcham commented on docker-compose.yaml
> +      - CONTEXTS_SCRIPTPATHS=/home/mircheq/IdeaProjects/s-pipes-modules;/home/mircheq/IdeaProjects/BP/s-pipes/doc/examples;
does not make sense to have concrete value to local folder

2023-05-03 14:09 UTC, blcham commented on s-pipes-web/src/main/java/cz/cvut/spipes/rest/SPipesServiceController.java
> +import org.springframework.web.bind.annotation.ExceptionHandler;
There are many files like that which does nothing, just reformat the code, we should remove it !!!!! Otherwise we won't be able to track the changes ... it is already 75 files in one pull request :(

2023-05-03 14:09 UTC, blcham commented on Dockerfile
> +COPY --from=MAVEN_BUILD /s-pipes-debug/target/s-pipes-debug-*.war /usr/local/tomcat/webapps/s-pipes-debug.war
I believe you should create your own Dockerfile, Dockerfile_rdf4j and docker-compose.yaml file in s-pipes-debug folder .... It is not the case that I want to use this setting for all the usecases that s-pipes is used for ... 

Also you should have s-pipes-debug/README.md where you mention it somehow for what it is used or something like that.

2023-05-03 14:09 UTC, blcham commented on s-pipes-model/src/main/java/cz/cvut/spipes/Vocabulary.java
> - * This class was generated by OWL2Java $VERSION$
should be reverted to here.

2023-05-03 14:12 UTC, blcham commented on Dockerfile
> +COPY --from=MAVEN_BUILD /s-pipes-debug/target/s-pipes-debug-*.war /usr/local/tomcat/webapps/s-pipes-debug.war
Moreover that should be separate github action that does the "s-pipes-engine-debug" package.

2023-05-04 14:27 UTC, mircheqtm commented on s-pipes-web/src/main/java/cz/cvut/spipes/rest/SPipesServiceController.java
> +import org.springframework.web.bind.annotation.ExceptionHandler;
There are not a lot of them, i went through all, and it's only 3

2023-05-10 19:21 UTC, blcham requested changes

2024-12-09 16:12 UTC, blcham commented
@palagdan relates to https://docs.google.com/document/d/1e7pV2NB4thdZ93cKRBDtMJUoBHWDQSkjA9-ds2EJn4w/edit?tab=t.0

2024-12-09 16:15 UTC, blcham commented
@palagdan we do not want to merge this, just create "same PR"

2025-03-21 14:34 UTC, blcham commented
This was already merged with #293

2025-03-21 14:34 UTC, closed without merging