[Fix] Get subjects from variable bindings (not model)
kbss-cvut/s-pipes pull request #159
Opened 2023-04-21 06:57 UTC by Matthew-Kulich

2023-04-21 08:11 UTC, blcham reviewed
I do not understand why you are getting "subjects" here. I would think that select query returns literals that you want to annotate. Is it the case ?

2023-04-21 08:14 UTC, Matthew-Kulich commented
I was creating IRI from the subject IRI, but we don't need to do that
```
 String newSubjectUri = subject.getURI() + "-annotated-" + DigestUtils.md5Hex(subject.getURI() + originalText);
```

2023-04-21 08:38 UTC, blcham commented
Not sure why you need to make IRI based on subject .. I would think that IRI would be dependant only based on literal itself... but maybe i don't see something...

2023-04-25 12:43 UTC, blcham requested changes
See my comments

2023-04-25 12:43 UTC, blcham commented on s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/TextAnalysisModule.java
> +                RDFNode object = solution.get("o");
Why "o", can't it be called anyhow, e.g. "l", "literal", ... ? Please add comments to the parameters of the module, so it is clear what it means (e.g. how to make query to retrieve literals)

2023-04-25 12:43 UTC, blcham commented on s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/TextAnalysisModule.java
> +                if (object != null && object.isLiteral() && object.asLiteral().getDatatype() instanceof XSDBaseStringType) {
I prefer to put log.warn in case it is not literal.

2023-04-25 12:43 UTC, blcham commented on s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/TextAnalysisModule.java
> +            if (counter > 0) {
Can we have log.debug somewhere to show that we processed next page? (so we are sure that something is happening ...)

2023-05-02 13:24 UTC, Matthew-Kulich commented on s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/TextAnalysisModule.java
> +                RDFNode object = solution.get("o");
Done

2023-05-02 13:46 UTC, blcham requested changes

2023-05-02 13:46 UTC, blcham commented on s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/TextAnalysisModule.java
> + * It uses an external web service to analyze text data and retrieve annotated text.
```suggestion
 * It uses an external web service to analyze text data and retrieve annotated text.
 * It analyse the text using a SKOS vocabulary that is stored in RDF4J repository.
```

2023-05-02 13:46 UTC, blcham commented on s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/TextAnalysisModule.java
> +    /** The name of the repository where the vocabulary is stored. */
BTW, it really uses vocabularyRepository ? Shouldn't it be password protected? I do not see where we use username/password here to acces it.

2023-05-02 18:44 UTC, Matthew-Kulich commented on s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/TextAnalysisModule.java
> +    /** A boolean flag indicating whether to replace the original text with the analyzed text. */
Deleting.

2023-05-02 18:45 UTC, Matthew-Kulich commented on s-pipes-modules/module-text-analysis/src/main/java/cz/cvut/spipes/modules/TextAnalysisModule.java
> +    /** The name of the repository where the vocabulary is stored. */
Yes, it uses the IRI of the vocabulary repository, it should be protected

2023-05-18 06:35 UTC, Matthew-Kulich commented
Ready to review @blcham

2023-05-18 07:45 UTC, blcham approved these changes

2023-05-18 10:20 UTC, merged