[Upd] Add new test for Rdf4jDeployModule
kbss-cvut/s-pipes pull request #187
Opened 2023-08-01 12:57 UTC by rodionnv

2023-08-02 16:34 UTC, blcham requested changes
The test does not really test anything ... It should be done in a same way as Rdf4jUpdateModule, moreover you are committing stuff that you do not use ... see my next commit.

2023-08-02 16:34 UTC, blcham commented on s-pipes-modules/module-rdf4j/pom.xml
> +            <artifactId>mockito-inline</artifactId>
watch out for commiting things that you do not use ... i believe i can remove it

2023-08-02 16:34 UTC, blcham commented on s-pipes-modules/module-rdf4j/pom.xml
> +            <version>3.4.0</version>
this version is inferred from that file and we can upgrade it at all places

2023-08-05 10:12 UTC, rodionnv commented on s-pipes-modules/module-rdf4j/src/test/java/cz/cvut/spipes/modules/Rdf4jDeployModuleTest.java
> +        moduleRdf4j.executeSelf();
resolved in the latest commits

2023-08-06 11:42 UTC, blcham requested changes
See my comments

2023-08-06 11:42 UTC, blcham commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +        repositoryManager = RepositoryProvider.getRepositoryManager(rdf4jServerURL);
The same way as we had in "rdf update module" we should have some kind of check if repository manager is already set in this situation and we try to load it from the configuration.

2023-08-06 11:42 UTC, blcham commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +    public void setConnection(RepositoryConnection connection) {
do not understand why we need this!  connection and repository can be created from repositoryManager ... so why we would like to set connection/repository to this class ---> if we allow this we would need to have special treatment for checking what should happen if :
- is set repositoryManager and connection at same time .... 

We do not need this. Since RepositoryManager can create connection and repository we can mock it by call getConnection() ... same way as we did in update module.

2023-08-06 11:42 UTC, blcham commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +    public void setRepository(Repository repository) {
see comment above.

2023-08-06 11:42 UTC, blcham commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +    public void setConnection(RepositoryConnection connection) {
I do not even understand why you need connection to have as java field ... even in tests you don't really use it

2023-08-06 11:42 UTC, blcham commented on s-pipes-modules/module-rdf4j/src/test/java/cz/cvut/spipes/modules/Rdf4jDeployModuleTest.java
> +        moduleRdf4j.setRdf4jContextIRI("");
If I would remove those line the test would behave the same right? So why do we have it here ? The main goal of the test is to communicate simple case that is tested it should be as short and clear as possible. I suggest to remove it unless you need it for some reason.

2023-08-06 11:42 UTC, blcham commented on s-pipes-modules/module-rdf4j/src/test/java/cz/cvut/spipes/modules/Rdf4jDeployModuleTest.java
> +    public void testDeployEmpty()  {
Lest's remove this test -- it is useless now.

2023-08-06 11:42 UTC, blcham commented on s-pipes-modules/module-rdf4j/src/test/java/cz/cvut/spipes/modules/Rdf4jDeployModuleTest.java
> +        verify(connection,times(1)).commit();
If you test commit() i would test also begin

But I thought that you will be testing that some kind of `add` method is called ...

2023-08-14 14:20 UTC, rodionnv commented on s-pipes-modules/module-rdf4j/src/test/java/cz/cvut/spipes/modules/Rdf4jDeployModuleTest.java
> +        verify(connection,times(1)).commit();
Done, `add()` is also tested

2023-08-14 14:21 UTC, rodionnv commented on s-pipes-modules/module-rdf4j/src/test/java/cz/cvut/spipes/modules/Rdf4jDeployModuleTest.java
> +        moduleRdf4j.setRdf4jContextIRI("");
Done

2023-08-14 14:23 UTC, rodionnv commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +        repositoryManager = RepositoryProvider.getRepositoryManager(rdf4jServerURL);
Done

2023-08-14 20:14 UTC, blcham commented
@rodionnv  still see 4 comments not answered.

2023-08-14 20:57 UTC, rodionnv commented on s-pipes-modules/module-rdf4j/pom.xml
> +            <artifactId>mockito-inline</artifactId>
Done

2023-08-14 20:57 UTC, rodionnv commented on s-pipes-modules/module-rdf4j/pom.xml
> +            <version>3.4.0</version>
Done

2023-08-14 21:00 UTC, rodionnv commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +    public void setConnection(RepositoryConnection connection) {
Done, this field was removed.

2023-08-14 21:01 UTC, rodionnv commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +    public void setRepository(Repository repository) {
Done, special check added to control if RepositoryManager is already set

2023-08-16 07:21 UTC, merged

2023-08-18 10:31 UTC, blcham commented
resolves #181