[New] Initial implementation of the xls files support in TabularModule
kbss-cvut/s-pipes pull request #203
Opened 2023-08-31 15:29 UTC by rodionnv

2023-09-02 14:50 UTC, blcham requested changes
@rodionnv I realized, the task is still quite hard and i decided to simplify it in #204 (do it first)

2023-09-02 14:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    private final Property P_PROCESS_SPECIFIC_SHEET_IN_XLS_FILE = getSpecificParameter("process-specific-sheet-in-xls-file");
We have already multiple filetypes so it is not effective anymore to represent it as boolean, please do it similar way as:
```
private Mode outputMode;
```

I would call property `getSpecificParameter("source-resource-format")` with mime-types concrete mime types, i.e.:
```
"text/csv" -- default
"text/tab-separated-values"
"text/html"
"application/vnd.ms-excel"
```

2023-09-02 14:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    private final Property P_PROCESS_SPECIFIC_SHEET_IN_XLS_FILE = getSpecificParameter("process-specific-sheet-in-xls-file");
do not forget to document it (add supported types into the comment)

2023-09-02 14:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +         assertTrue(outputContext.getDefaultModel().size() > 0);
Use `assertIsomorphic(actualModel, expectedModel)`  as I want to check what will be actual output of the transformation !

2023-09-02 14:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +         module.setProcessSpecificSheetInXLSFile(2);
We should also be able to process all sheets of xlsx file together forming multiple 
```
[ a       <http://www.w3.org/ns/csvw#TableGroup> ;
  <http://www.w3.org/ns/csvw#table>  
        [ a       <http://www.w3.org/ns/csvw#Table>  ; ... ] ;
        [ a       <http://www.w3.org/ns/csvw#Table> ; .... ] ;
        [ a       <http://www.w3.org/ns/csvw#Table> ; .... ] ;
```

2023-09-02 14:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +         module.setProcessSpecificSheetInXLSFile(2);
There are plenty JUNIT tests, go over it and understand what is
```
http://www.w3.org/ns/csvw#TableGroup
http://www.w3.org/ns/csvw#Table
```

2023-09-02 14:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +         module.setProcessSpecificSheetInXLSFile(2);
I mean excel file represent TableGroup and one sheet is a Table.

2023-09-02 14:50 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +    public StringStreamResource convertToTSV(StreamResource streamResource,int sheetNumber){
will this converter work with merged cells and rows ? will you be able to detect after this transformation ?

2023-09-04 13:40 UTC, rodionnv commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    private final Property P_PROCESS_SPECIFIC_SHEET_IN_XLS_FILE = getSpecificParameter("process-specific-sheet-in-xls-file");
Please, check this [commit](https://github.com/kbss-cvut/s-pipes/pull/203/commits/40cbad8aa08422649c8e6ca6dd0582bd91407b12) if it resolves this suggestion

2023-09-04 14:57 UTC, rodionnv commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +    public StringStreamResource convertToTSV(StreamResource streamResource,int sheetNumber){
This converter works with merged cells and rows but for now it writes value from the merged cells only once and skips it in other occurrences, and it's not possible to query which columns and rows were merged. I am not yet sure how exactly this information will be represented in the output. I think that one way to do it is to have something like this:

<http://test-file#row-2>
    ex:mergedColumns1 "b0" , "b1" ;
    ex:mergedColumns2 "b2" , "b3" .

_:b0
    ex:mergedRows1 <http://test-file#row-3> , <http://test-file#row-4> .

2023-09-05 14:46 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +    public StringStreamResource convertToTSV(StreamResource streamResource,int sheetNumber){
I just started to think about it (does not contain much advice):
- it does not make sense to merge whole rows or whole columns (as it just became single row/column), thus we are not really merging columns or rows but cells
- we can consider one cell as master cell in merged group of cell -- i.e. the most top-left cell we can call master and other can be said that are just "duplicates"

2023-09-05 15:16 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +    public StringStreamResource convertToTSV(StreamResource streamResource,int sheetNumber){
@rodionnv what do you think about it ?

2023-09-05 15:32 UTC, rodionnv commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +    public StringStreamResource convertToTSV(StreamResource streamResource,int sheetNumber){
@blcham Yes, I think this is a better way to do this. 
By the way, I have noticed that for some reason in the output model, column indexes are sometimes not in the right order, like in this example:
![image](https://github.com/kbss-cvut/s-pipes/assets/130922166/4036faf4-77d9-42ab-8714-6be43e6ea0a8)
I am not sure if this won't cause issues with suggested approach

2023-09-08 20:48 UTC, blcham requested changes

2023-09-13 07:17 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    private final Property P_SOURCE_RESOURCE_FORMAT = getSpecificParameter("source-resource-format");
This is not consistent with the fact that you are processing resources no literal values.
In code you have `$prefix/text/plain` not `"text/plain"`

2023-09-13 07:17 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            setDelimiter('\t');
Do you address the fact that cells can contain "\t" in text?

2023-09-13 07:17 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +                    "text/tsv"
This constant cannot be here !!!

2023-09-13 07:23 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    private final Property P_PROCESS_SPECIFIC_SHEET_IN_XLS_FILE = getSpecificParameter("process-specific-sheet-in-xls-file");
In principle, it is ok but see my other comments (we want to change Resource --> string literal)

2023-09-13 07:30 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/countries_model.ttl
> +          [ a       <http://www.w3.org/ns/csvw#Table> ;
TAB=sheet

2023-09-13 07:46 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +                    "text/tsv"
Check also HTML2TSVConvertor

2023-09-13 08:03 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +    public StringStreamResource convertToTSV(StreamResource streamResource,int sheetNumber){
This will be resolved in https://github.com/kbss-cvut/s-pipes/issues/215

2023-09-13 08:06 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/countries_model.ttl
> +          [ a       <http://www.w3.org/ns/csvw#Table> ;
Try to put also name of CSV file in #table property and #TableGroup could contain name of excel file.

2023-09-13 08:16 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/countries_model.ttl
> +          [ a       <http://www.w3.org/ns/csvw#Table> ;
Implementation should extend classes such as Table.java with field annotated by e.g. rdfs:label, then you need to set this field and persistence (=saving into RDF)  will be handled automatically. This is managed by our framework [JOPA](https://github.com/kbss-cvut/jopa), which is very similar to [JPA](https://cs.wikipedia.org/wiki/Java_Persistence_API)

JOPA -- manages mapping between Java entities and RDF ontologies
JPA - manages mapping between Java entities and relational database

2023-09-13 08:16 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/countries_model.ttl
> +          [ a       <http://www.w3.org/ns/csvw#Table> ;
Watch some 5-10 minutes tutorial for JPA .

2023-09-17 17:43 UTC, rodionnv commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ResourceFormat.java
> +    public Resource getResource() {
Resolved in [here](https://github.com/kbss-cvut/s-pipes/pull/203/commits/1a9d0b840ca16a4f5c7107a45d2dbaf27b3ba22f)

2023-09-17 17:43 UTC, rodionnv commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLS2TSVConvertor.java
> +                    "text/tsv"
Resolved in [here](https://github.com/kbss-cvut/s-pipes/pull/203/commits/1a9d0b840ca16a4f5c7107a45d2dbaf27b3ba22f)

2023-09-17 21:08 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ResourceFormat.java
> -        return ResourceFactory.createResource(PREFIX + this.localName);
This does not make sense to me ... 
1) why creating resource? I can imagine creating string literal which is not resource ?
2) Why calling it `localName`?How about calling it value, or something that make sense? LocalName is term from URI terminology, which does not make sense in this case.

2023-09-17 21:08 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ResourceFormat.java
> +    public Resource getResource() {
I wrote comment https://github.com/kbss-cvut/s-pipes/pull/203/commits/1a9d0b840ca16a4f5c7107a45d2dbaf27b3ba22f#r1328144959

2023-09-17 21:11 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ResourceFormat.java
> +    public Resource getResource() {
I wrote comment:
> This does not make sense to me ...
> 
> 1. why creating resource? I can imagine creating string literal which is not resource ?
> 2. Why calling it `localName`?How about calling it value, or something that make sense? LocalName is term from URI terminology, which does not make sense in this case.

2023-09-18 21:39 UTC, rodionnv commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ResourceFormat.java
> +    public Resource getResource() {
I have refactored it in this [commit](https://github.com/kbss-cvut/s-pipes/pull/203/commits/89a0946355b8f5726406af3377190ec39365c723). Please check if it meets the requirements now.

2023-09-21 12:54 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +        table = onTable(null);
I am not sure here if it is good idea to create TableGroup and Table before being able to find out input format, but maybe it is ok :)

2023-09-21 13:59 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + * Take a look at the option {@link TabularModule#sourceResourceFormat} and class {@link HTML2TSVConvertor} for more details.
We should reformulate.

2023-09-21 14:23 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            LOG.debug("Using comma as default value to be compliant with RFC 4180 (CSV).");
This is strange ... It seems like we always show this message but we should not.

2023-09-29 13:50 UTC, blcham approved these changes
LGTM

2023-09-29 14:00 UTC, merged