Issues/issue205 module creator plugin outputs wrong rdf
kbss-cvut/s-pipes pull request #210
Opened 2023-09-11 10:20 UTC by kostobog

Fixes #205, #206

#205
- delete incorrect sharing of parameter declaration among modules in writeConstraintsToModel
- add subClassOf triple to modules extending other modules, including abstract ones, to share parameter declaratoin with their super classes.
- Note that tools using the generated descriptions of modules that extend other modules will have to query the super classes for their parameter declaration.

#206
- Add SPipesModule and Param

2023-09-11 12:50 UTC, kostobog commented
Review notes:
- Abstract classes should not be converted to modules.
- specify comments of parameters from javadoc and `s-pipes-modules` project.
- this should be copied in all-modules.ttl do not include triples where the resource is the ontology. See module `module-text-analysis.ttl` in resource folder of `moodule-text-analysis` .

2023-09-12 08:45 UTC, blcham requested changes
Did not go over it extensively yet.

2023-09-12 08:45 UTC, blcham commented on s-pipes-modules/module-dataset-discovery/src/main/java/cz/cvut/spipes/modules/DatasetDiscoveryModule.java
> +    @Parameter(urlPrefix = TYPE_URI + "/", name = "prp-user-inpu")
?

2023-09-12 08:45 UTC, blcham commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/ConstructFormMetadataModule.java
> +@SPipesModule(label = "construct form metadata", comment = "Compute form:has-origin-path and form:has-origin-path-id properties.")
Duplicate comment -- leave it only in the annotation.

2023-09-12 08:45 UTC, blcham commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/ConstructTextualViewModule.java
> +@SPipesModule(label = "construct textual view", comment =
Duplicate comment.

Just note, in JAVA 15 we will use text blocks to make it more readable, see https://www.baeldung.com/java-multiline-string

2023-09-12 08:45 UTC, blcham commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/FetchPossibleValuesModule.java
> +@SPipesModule(label = "fetch possible values", comment =
duplicate comment

2023-09-12 08:45 UTC, blcham commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/MergeFormMetadataModule.java
> +@SPipesModule(label = "merge form metadata", comment =
duplicate comment

2023-09-12 08:45 UTC, blcham commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +@SPipesModule(label = "deploy", comment =
duplicate comment

2023-09-12 08:45 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/RDF2CSVModule.java
> +@SPipesModule(label = "RDF2CSV", comment = "Module for converting RDF (representing table) to CSV. " +
duplicate comment

2023-09-18 15:48 UTC, kostobog commented on s-pipes-modules/module-dataset-discovery/src/main/java/cz/cvut/spipes/modules/DatasetDiscoveryModule.java
> +    @Parameter(urlPrefix = TYPE_URI + "/", name = "prp-user-inpu")
Not sure, what is wrong here. Can you elaborate?

2023-09-19 10:09 UTC, kostobog commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/RDF2CSVModule.java
> +@SPipesModule(label = "RDF2CSV", comment = "Module for converting RDF (representing table) to CSV. " +
done.

2023-09-19 10:09 UTC, kostobog commented on s-pipes-modules/module-rdf4j/src/main/java/cz/cvut/spipes/modules/Rdf4jDeployModule.java
> +@SPipesModule(label = "deploy", comment =
done.

2023-09-19 10:09 UTC, kostobog commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/MergeFormMetadataModule.java
> +@SPipesModule(label = "merge form metadata", comment =
done.

2023-09-19 10:09 UTC, kostobog commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/FetchPossibleValuesModule.java
> +@SPipesModule(label = "fetch possible values", comment =
done.

2023-09-19 10:09 UTC, kostobog commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/ConstructTextualViewModule.java
> +@SPipesModule(label = "construct textual view", comment =
done.

2023-09-19 10:10 UTC, kostobog commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/ConstructFormMetadataModule.java
> +@SPipesModule(label = "construct form metadata", comment = "Compute form:has-origin-path and form:has-origin-path-id properties.")
done.

2023-09-19 10:10 UTC, kostobog commented on s-pipes-modules/module-dataset-discovery/src/main/java/cz/cvut/spipes/modules/DatasetDiscoveryModule.java
> +    @Parameter(urlPrefix = TYPE_URI + "/", name = "prp-user-inpu")
done.

2023-09-27 06:49 UTC, blcham commented on s-pipes-modules/module-dataset-discovery/src/main/java/cz/cvut/spipes/modules/DatasetDiscoveryModule.java
> +    @Parameter(urlPrefix = TYPE_URI + "/", name = "prp-user-inpu")
name = "prp-user-inpu" vs. getParameter("prp-user-input")

2023-09-27 06:53 UTC, blcham commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/ConstructFormMetadataModule.java
> +@SPipesModule(label = "construct form metadata", comment = "Compute form:has-origin-path and form:has-origin-path-id properties.")
@kostobog  I do not see where it was done.

2023-09-27 06:54 UTC, blcham commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/ConstructTextualViewModule.java
> +@SPipesModule(label = "construct textual view", comment =
not done yet

2023-09-27 08:43 UTC, blcham commented
@kostobog please create separate ticket for https://github.com/kbss-cvut/s-pipes/pull/210/commits/7152270bee474eded021edeed438d8d5b6b614a6

2023-09-27 13:32 UTC, kostobog commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/ConstructTextualViewModule.java
> +@SPipesModule(label = "construct textual view", comment =
Should be done now.

2023-09-27 13:32 UTC, kostobog commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/FetchPossibleValuesModule.java
> +@SPipesModule(label = "fetch possible values", comment =
Should be done now.

2023-09-27 13:32 UTC, kostobog commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/MergeFormMetadataModule.java
> +@SPipesModule(label = "merge form metadata", comment =
Should be done now.

2023-09-27 13:32 UTC, kostobog commented on s-pipes-modules/module-dataset-discovery/src/main/java/cz/cvut/spipes/modules/DatasetDiscoveryModule.java
> +    @Parameter(urlPrefix = TYPE_URI + "/", name = "prp-user-inpu")
done

2023-09-27 13:33 UTC, kostobog commented on s-pipes-modules/module-form/src/main/java/cz/cvut/spipes/modules/ConstructTextualViewModule.java
> +@SPipesModule(label = "construct textual view", comment =
Should be done now.

2023-09-27 13:37 UTC, kostobog commented
Javadoc comments are moved into annotations.
Copying manually managed ontology with module descriptions from root of resource folder to `all-modules.ttl` implemented. 
The output `all-modules.ttl` is formatted using frames.

2023-09-29 20:21 UTC, blcham commented on s-pipes-modules-utils/s-pipes-module-creator-maven-plugin/src/main/java/RdfAnnotationProcessorMojo.java
> +     * id of the sub-project followed by the postfix ".sms.tll". For example, assume the input parameter project
@kostobog FYI, resolve when you read the comment

2023-09-29 20:31 UTC, merged