Tabular module
kbss-cvut/s-pipes pull request #23
Opened 2021-10-01 09:51 UTC by Sidonivs

Implementation of the default configuration of the tabular module

2021-10-04 11:35 UTC, blcham requested changes
Beside the comment about isDuplicate, it seems fine.

I had little trouble to check as I was expecting some documentation of the module to compare implementation with.

2021-10-04 11:35 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                boolean isDuplicate = !columnNames.add(columnTitle);
shouldn't be columnNames.add(columnName) ? I think you should find out if isDuplicate is related to normalized name and not the title

2021-10-12 09:25 UTC, blcham requested changes
See my comments about documentation.

2021-10-19 19:24 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> + *                 "http://test-file#row-{_row}"^^csvw:uriTemplate ;
Also as i mentioned in previous comment "Describe how we transform columnName from columnTitle -- if it is not part of the specificaiton"

2022-09-13 11:49 UTC, Matthew-Kulich commented
@blcham We don't need this anymore. We should delete it IMO

2022-09-13 11:51 UTC, closed without merging