Fixed issue 231
kbss-cvut/s-pipes pull request #240
Opened 2024-07-04 13:31 UTC by MSattrtand

Fixed issue 231.
![image](https://github.com/kbss-cvut/s-pipes/assets/93949007/a8c87ec8-590e-42c0-9dc3-41605204c628)
If an incorrect query causes an exception, the query is logged now.

2024-07-04 14:27 UTC, blcham commented
1) for referencing issues use # ... as it is very well integrated with github  + use more specific commits:
     Fixed issues 231 ---> [#231] Improve logging for queries when parse error occurs

2024-07-04 18:18 UTC, MSattrtand commented
The stack trace shows that the exception has occurred at the perform function of the ParserARQ class right here:
![image](https://github.com/kbss-cvut/s-pipes/assets/93949007/b498b4b3-f2d1-42c7-9785-5d498a07b6ec)
The last of the s-pipes functions that may cause the exception are ApplyConstructModule and BindBySelectModule, so if we assume that foreign libraries are working correctly, the main reason the parser may fail is that our query is truly incorrect. Therefore, I thought logging only the query and the stack trace was enough for debugging.
NB: There are more functions that may (theoretically) send incorrect queries to the parser; ApplyConstructModule and BindBySelectModule are the only modules I can properly test because they are called during the execution of the Hello, World script.

2024-07-05 04:45 UTC, blcham commented
> The stack trace shows that the exception has occurred at the perform function of the Parse .....

Not sure what you mean, but I am saying that the error you are logging is not good enough because you won't be able to find the error within the query. Try to read what you sent me above and find the error based on the coordinates: in you output:
`line:32 column 7`

2024-07-05 05:32 UTC, blcham requested changes
@MSattrtand I created a new PR -- https://github.com/kbss-cvut/s-pipes/pull/241.

Also see my comments here -- https://github.com/kbss-cvut/s-pipes/issues/231#issuecomment-2210212910

Read my comments, close this PR, and continue work on the newly provided PR (make new PRs to merge to this branch)

2024-07-05 05:32 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/ApplyConstructModule.java
> -            .stream().map(r -> r.as(Construct.class))
I do not understand why you get so many formatting changes. We should investigate what the difference is in our setting (maybe use some kind of prettifier of the code to enforce the same formatting).

Anyway, if having too many formatting changes, do the formatting in a separate commits so the actual change is readable.

2024-07-05 05:32 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/BindBySelectModule.java
> +        catch (Exception e) {
you are duplicating this part of code with the one above ... we need to use some utility function

2024-07-05 05:32 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/ApplyConstructModule.java
> +                catch (Exception e) {
we are trying to describe QueryParseException not generic exception.

2024-07-05 07:08 UTC, blcham commented
@MSattrtand see my comments and https://github.com/kbss-cvut/s-pipes/pull/241

2024-07-08 21:44 UTC, closed without merging