Updated README.md to provide instructions for running the SPipes Dock…
kbss-cvut/s-pipes pull request #242
Opened 2024-07-10 16:00 UTC by palagdan

…er container without mounting directories, and added optional steps for mounting directories on both Linux and Windows.

2024-07-11 13:00 UTC, blcham commented
I will review during weekend

2024-07-15 15:04 UTC, blcham requested changes
I have one comment to discuss. After resolution I would make the description more concise -- i.e. have one guide with steps and differentiate only within steps (regarding Windows and Linux)

2024-07-15 15:04 UTC, blcham commented on README.md
> +`docker run -v C:\Users\[YourUsername]\Documents:/home -p 8080:8080 s-pipes-engine:latest`
We need to discuss this at the next meeting. This mount would work but would be useless as it is not an alternative to:
> The `-v /home:/home` option mount your home to docker image - this is very convenient for testing.

2024-07-15 15:04 UTC, blcham commented on README.md
> +`docker run -v C:\Users\[YourUsername]\Documents:/home -p 8080:8080 s-pipes-engine:latest`
Probably the easiest way to fix it is to not have it for Windows at all.

2024-07-15 19:44 UTC, palagdan commented on README.md
> +`docker run -v C:\Users\[YourUsername]\Documents:/home -p 8080:8080 s-pipes-engine:latest`
When I was working on this issue, I thought that the user could mount any directory on their local machine.

2024-07-15 23:40 UTC, blcham commented on README.md
> +`docker run -v C:\Users\[YourUsername]\Documents:/home -p 8080:8080 s-pipes-engine:latest`
No, I believe the point here was to align "host" paths to "s-pipes-engine docker image" paths, i.e.:
- if I would have a script in `/home/blcha/projects/s-pipes/doc/example/hello-world.sms.ttl` and an error occurs in loading the script within the "docker image", I could use the path from the log file generated by "s-pipes docker image" in my "host"

2024-07-15 23:43 UTC, blcham commented on README.md
> +`docker run -v C:\Users\[YourUsername]\Documents:/home -p 8080:8080 s-pipes-engine:latest`
To have the same functionality I think you would have to mount something from the link that i provided you here:
https://github.com/kbss-cvut/s-pipes/issues/238#issuecomment-2220430925

To be more precise I guess this is relevant part of the link:
```
if running docker-compose.exe or spe.bat in windows (not docker in wsl distribution) add the :
SHARED_ROOT=/host_mnt/c
PWD=/host_mnt/$PROJECT_ROOT should be absolute path
if running docker-compose or spe.sh in wsl distribution, set variables as follows:
SHARED_ROOT=/mnt/c
```

2024-07-16 11:18 UTC, palagdan commented on README.md
> +`docker run -v C:\Users\[YourUsername]\Documents:/home -p 8080:8080 s-pipes-engine:latest`
This section is only appliable for wsl distributions : /host_mnt/c is a path in wsl. I don't know how to apply it to windows FS.

2024-07-17 08:29 UTC, blcham commented
@palagdan I reformulated a little what you wrote; now I consider it final ... let me know what u think

2024-07-17 08:47 UTC, palagdan commented
> @palagdan I reformulated a little what you wrote; now I consider it final ... let me know what u think

Thank you for the update. I agree with your changes and consider it final as well.

2024-07-17 10:40 UTC, merged