Update/239 jdk 17
kbss-cvut/s-pipes pull request #243
Opened 2024-07-15 11:20 UTC by palagdan

2024-07-15 11:39 UTC, blcham commented
@palagdan upgrade in dockerfile as well

2024-07-15 23:52 UTC, blcham commented
@palagdan 

FYI, to use referencing u must use a hash character, i.e.:
`[239] README.md updated. JDK17 -> JDK21 --> [#239] README.md updated. JDK17 -> JDK21`

2024-07-16 10:49 UTC, palagdan commented
The last version of openjdk for maven that I found is maven:3.8.7-openjdk-18. From https://hub.docker.com/_/maven/tags?page=&page_size=&ordering=&name=openjdk-18.

2024-07-16 10:53 UTC, palagdan commented
Additionally, I am unable to update the JDK version in Maven due to a dependency issue with org.aspectj. I tried to update this version, but encountered an error elsewhere.

2024-07-16 11:18 UTC, blcham commented
> Additionally, I am unable to update the JDK version in Maven due to a dependency issue with org.aspectj. I tried to update this version, but encountered an error elsewhere. I believe updating dependencies should be handled in a separate ticket.

Please be more specific ... as it might be used as input to decide whether/when to update.

2024-07-16 11:19 UTC, blcham requested changes
See my comments.

2024-07-16 11:19 UTC, blcham commented on README.md
> +- JDK 21
I believe this is wrong right? It does not work with JDK 21, right? From what i understood

I suggest to put here `JDK 17, or 18`

2024-07-16 11:41 UTC, palagdan commented on README.md
> +- JDK 21
I tested it with jdk 21 and it works fine.

2024-07-16 11:57 UTC, palagdan commented
> > Additionally, I am unable to update the JDK version in Maven due to a dependency issue with org.aspectj. I tried to update this version, but encountered an error elsewhere. I believe updating dependencies should be handled in a separate ticket.
> 
> Please be more specific ... as it might be used as input to decide whether/when to update.

When I tried to change <jdk.version>1.8</jdk.version> to <jdk.version>17</jdk.version>  I got this error: 

![Screenshot 2024-07-16 133919](https://github.com/user-attachments/assets/f15747bc-7ee8-4b8e-abb9-e3bdc9117e28)

Then I decided to update the version of <org.aspectj.version>1.9.7</org.aspectj.version> to <org.aspectj.version>1.9.20</org.aspectj.version> and  I got this error: 

![Screenshot 2024-07-16 135417](https://github.com/user-attachments/assets/90598578-353a-4468-ba1f-d60f2768a7c9)

2024-07-16 12:40 UTC, blcham commented on README.md
> +- JDK 21
Not sure if u are not mixing 2 different things:
- requirement to run s-pipes-engine
- requirement to build s-pipes-engine

2024-07-16 19:14 UTC, blcham commented on Dockerfile
> +FROM maven:3.9.8-amazoncorretto-21-al2023 AS MAVEN_BUILD
Not sure, what was motivation to choose image that targets enhancements and optimizations tailored for performance, security, and integration with AWS services.

.. but I guess it is acceptable.

2024-07-16 19:14 UTC, blcham commented on Dockerfile
> +FROM maven:3.9.8-amazoncorretto-21-al2023 AS MAVEN_BUILD
Not sure, what was motivation to choose image that targets enhancements and optimizations tailored for performance, security, and integration with AWS services.

.. but I guess it is acceptable.

2024-07-16 19:15 UTC, blcham commented
tests are still failing

2024-07-21 03:55 UTC, blcham commented on Dockerfile
> +FROM maven:3.9.8-amazoncorretto-21-al2023 AS MAVEN_BUILD
@palagdan since you did not provide be any reasoning behind choosing amazoncorretto -- I decided to use maven:3-eclipse-temurin-17 as it is  free and open-source JDK with quite popularity and good support.

2024-07-21 04:01 UTC, blcham commented
@palagdan At the end, I fixed GH actions with df7d7308839be92fc50b091198c6a38417c09c18

2024-07-21 04:02 UTC, merged