Annotation inject logs 244
kbss-cvut/s-pipes pull request #247
Opened 2024-07-24 10:41 UTC by palagdan

Resolves #244

2024-07-24 11:04 UTC, blcham commented
@palagdan I assume you know that build is failing

2024-07-27 21:45 UTC, blcham requested changes
See my suggestions.

2024-07-27 21:45 UTC, blcham commented on s-pipes-cli/pom.xml
> +            <version>1.18.24</version>
A version of the library should not be duplicated multiple times because it is then harder to upgrade. For that purpose, we have the [dependencyManagement](https://github.com/kbss-cvut/s-pipes/blob/038b35026980cd230dae1fe8e3cab9b04382a440/s-pipes-parent/pom.xml#L34) section in parent pom.xml. Add this library there so you do not have to put an explicit version here.

2024-07-27 21:45 UTC, blcham commented on s-pipes-core/pom.xml
> +            <version>1.18.24</version>
It should be in parent pom.xlml; see comment above, and there are other 12 places where it happens as well; please remove it.

2024-07-29 10:25 UTC, palagdan commented on s-pipes-cli/pom.xml
> +            <version>1.18.24</version>
Ok, I remove versions from children's pom.xml and add specified version to the parent pom.xml

2024-07-29 18:39 UTC, palagdan commented
@blcham 
I removed versions from all children pom.xml and added it to parent pom.xml

2024-07-30 12:51 UTC, merged