[#246] Add RestExceptionHandler for handling validationConstraintFail…
kbss-cvut/s-pipes pull request #248
Opened 2024-07-24 17:33 UTC by palagdan

…edException and return detailed information about exception

Resolves #246

2024-07-27 23:20 UTC, blcham commented
I guess we should discuss how to implement this on a meeting. To me it seems best to implement it by extending s-pipes-model:
![image](https://github.com/user-attachments/assets/04c70dfa-2611-439d-b7e4-4d870d137123)

Then I would like to output through REST API something like:
```
{
  "@context": {
    "variable1": "http://onto.fel.cvut.cz/ontologies/s-pipes/variable1",
    "variable2": "http://onto.fel.cvut.cz/ontologies/s-pipes/variable2",
    "module": "http://onto.fel.cvut.cz/ontologies/s-pipes/module",
    "message": "http://onto.fel.cvut.cz/ontologies/s-pipes/message",
    "constraintQuery": "http://onto.fel.cvut.cz/ontologies/s-pipes/constraintQuery",
    "constraintFailureEvidences": "http://onto.fel.cvut.cz/ontologies/s-pipes/constraintFailureEvidences",
    "ValidationConstraintError": "http://onto.fel.cvut.cz/ontologies/s-pipes/ValidationConstraintError"
  },
  "@type": "ValidationConstraintError",
  "module": "ExampleModule",
  "message": "Example error message",
  "constraintQuery": "SELECT ?variable1 ?variable2 WHERE { ... }",
  "constraintFailureEvidences": [
    {
      "variable1": "value1_1",
      "variable2": "value1_2"
    },
    {
      "variable1": "value2_1",
      "variable2": "value2_2"
    }
  ]
}
```

We can also think of existing VariableBinding model.

2024-07-27 23:30 UTC, blcham requested changes
Please fix comments that makes sense and we discuss the rest.

2024-07-29 18:16 UTC, palagdan commented on s-pipes-web/src/main/java/cz/cvut/spipes/rest/handler/ErrorValidationResponse.java
> +    public List<Map<String, String>> getEvidences() {
Sorry, I don't understand: 

> to have for rows

I chose this format because it is the most suitable solution for transferring rows via JSON/JSON-LD. I implemented the printTable function to log the table of evidence in this format.

2024-07-29 18:19 UTC, palagdan commented on s-pipes-web/src/main/java/cz/cvut/spipes/rest/handler/ErrorValidationResponse.java
> +public class ErrorValidationResponse {
I named it ErrorValidationResponse because it is a DTO used for transferring data related to a validation error response. If you prefer the name ValidationError, I can refactor it accordingly.

2024-07-29 18:24 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/exception/ValidationConstraintFailedException.java
> +                                               List<Map<String, String>> evidences) {
If I understand correctly, you want to obtain a ValidationErrorResponse directly from this exception. However, this doesn't make much sense to me because ValidationErrorResponse is a DTO used for the business logic(response part) of the backend.

2024-07-29 18:27 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/config/EvidenceConfig.java
> +        return Integer.parseInt(CoreConfigProperies.get("evidence.number", "3"));
Should I use the last name in config-core:
> execution.validation.maxNumberOfConstraintFailureEvidences

and retrieve this value from a method in ExecutionConfig?

2024-07-31 06:13 UTC, blcham commented on s-pipes-web/src/main/java/cz/cvut/spipes/rest/handler/ErrorValidationResponse.java
> +    public List<Map<String, String>> getEvidences() {
OK, I understand it now, sorry for confusion.

2024-07-31 06:18 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/config/EvidenceConfig.java
> +        return Integer.parseInt(CoreConfigProperies.get("evidence.number", "3"));
Yes, all should be implemented in ExecutionConfig and execution.checkValidationConstraints  should be refactored.

2024-08-01 15:20 UTC, palagdan commented
@blcham If I remove list, then I get this :
![Screenshot from 2024-08-01 17-02-54](https://github.com/user-attachments/assets/e1a917db-b858-4b22-ac66-50873c0f1a45)

2024-08-02 08:52 UTC, blcham commented
@palagdan still some unresolved issues in source code:
> // TODO "module" is missing

2024-08-02 10:20 UTC, palagdan commented
@blcham Should I just add:   
```java
model.add(validationError, getP("module"), "ValidationConstraintModule");
```

2024-08-02 14:41 UTC, blcham commented
No, it must be the module in which the validation error occurred, i.e., the module within the pipeline to which the validation constraint is attached.

2024-08-06 13:49 UTC, blcham commented
@palagdan Final output looks like this:
![image](https://github.com/user-attachments/assets/da13f2ae-9b61-4b33-afa3-669edeabbdc0)

2024-08-06 13:56 UTC, blcham commented on s-pipes-web/src/main/java/cz/cvut/spipes/rest/handler/ErrorValidationResponse.java
> +public class ErrorValidationResponse {
ok

2024-08-06 14:00 UTC, blcham approved these changes

2024-08-06 14:00 UTC, merged