[#76] Change toString in VariablesBinding to not showing basic types …
kbss-cvut/s-pipes pull request #250
Opened 2024-07-31 07:58 UTC by palagdan

…of variables

Resolves #76 

![Screenshot from 2024-07-31 09-53-31](https://github.com/user-attachments/assets/0c4d6a13-0de1-479c-b3be-a40632f77fb0)

In the picture, there are examples of string, int, boolean and Uri bindings

2024-08-09 09:47 UTC, blcham requested changes
See my comments

2024-08-09 09:47 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/engine/VariablesBinding.java
> +        StringBuilder sb = new StringBuilder();
I would use rather stream API and specific function:
`private static toString(RDFNode node)`

The implementation could look like:
return binding.asMap().entrySet().stream().map((k,v) -> new EntrySet(k, toString(v)).toString();

Maybe search if toString(RDFNode) is not a directly a function in RDFNode.

2024-08-10 13:29 UTC, blcham approved these changes
@palagdan looks nice now, I have one more suggestion, which I did not however test ... if you like it more apply it otherwise leave it as it is and you can merge this PR, **but squash commits first**.

2024-08-10 13:29 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/engine/VariablesBinding.java
> +
```suggestion
```

2024-08-10 13:29 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/engine/VariablesBinding.java
> +                .collect(Collectors.joining(", ", "{", "}"));
Not sure but isn't it same as:
```suggestion
        return binding.asMap()
                    .entrySet()
                    .stream()
                    .collect(Collectors.toMap(
                         Map.Entry::getKey, 
                         e -> toString(e.getValue())
                     ))
                     .toString();
```

2024-08-12 15:37 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/engine/VariablesBinding.java
> +        StringBuilder sb = new StringBuilder();
done.

2024-08-14 07:59 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/engine/VariablesBinding.java
> +
done

2024-08-14 08:00 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/engine/VariablesBinding.java
> +                .collect(Collectors.joining(", ", "{", "}"));
done

2024-08-14 08:03 UTC, merged