[#219] Remove loadConfiguration wherever it possible and add paramete…
kbss-cvut/s-pipes pull request #252
Opened 2024-08-06 06:28 UTC by palagdan

…r annotation to the attributes. Change loadConfiguration to support assign RDFNode itself.

Resolves #219

2024-08-06 06:33 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/constants/SM.java
I made it public because this is a final constant used in the @Parameter annotation. It should be accessed directly, not via a getter, as annotations are configured at compile time rather than runtime.

2024-08-07 13:37 UTC, blcham requested changes
See my comments, then I will review it again.

2024-08-07 13:37 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/BindBySelectModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "selectQuery", comment = "")
This is strange to have empty comment, how about not making it required?

2024-08-07 13:37 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/BindBySelectModule.java
> +//    @Override
let's remove this.

2024-08-07 13:37 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/BindBySelectModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "selectQuery", comment = "")
See also other lines like this.

2024-08-07 13:37 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/BindBySelectModule.java
> +//    @Override
and see similar places as well

2024-08-07 13:39 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/constants/SM.java
@palagdan OK, I unified it everywhere with this commit:
https://github.com/kbss-cvut/s-pipes/commit/fe991de2f6308b257d7b0aaebab1b820f301130a

2024-08-08 07:51 UTC, blcham requested changes
See my comments. 

Please add tests for specific handlers to understand how they behave.

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/ImportRDFFromWorkspaceModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "baseURI")
This will not work properly with StringHandler as you are not using getEffectiveValue but instead you are using plain value, see my comment at StringHandler ...

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/StringHandler.java
> +        Statement s = resource.getProperty(property);
Should be effective value instead. Note that effective value is extension of this processing which allows to put expression there instead of final (constant) value.

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/StringHandler.java
> +        Statement s = resource.getProperty(property);
Please do the following:
- make a test and make sure that is failing
- implement it correctly
- make sure test passes

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/RDFNodeHandler.java
> +    public void setValueByProperty(Property property) {
must be effective value.

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BooleanHandler.java
> +    public void setValueByProperty(Property property) {
Add effective value instead.

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/BindWithConstantModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "value")
will not work due to effective value issue.

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/ImportRDFFromWorkspaceModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "sourceFilePath")
Will not work as it does not process effective value.

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/PathHandler.java
> +    public void setValueByProperty(Property property) {
Implement effective value.

2024-08-08 07:51 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/IntegerHandler.java
> +    public void setValueByProperty(Property property) {
Implement effective value.

2024-08-08 08:41 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/StringHandler.java
> +        Statement s = resource.getProperty(property);
ok, I will make test for each handler.

2024-08-08 08:45 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/ImportRDFFromWorkspaceModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "baseURI")
I implement string handlers and other types this way because, in `loadConfiguration()`, these types were not configured with the effective value. I'll correct all these handlers.

2024-08-08 09:14 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/ImportRDFFromWorkspaceModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "baseURI")
Do not understand what you mean, as for example, `baseUri` was loaded in the following way:
```
baseUri = getEffectiveValue(SML.baseURI).asLiteral().getString();
```

2024-08-15 08:58 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/RDFNodeHandler.java
> +    public void setValueByProperty(Property property) {
done

2024-08-15 08:58 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/BindWithConstantModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "value")
done

2024-08-15 08:58 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/ImportRDFFromWorkspaceModule.java
> +    @Parameter(urlPrefix = SML.uri, name = "sourceFilePath")
done

2024-08-15 08:58 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/PathHandler.java
> +    public void setValueByProperty(Property property) {
done

2024-08-15 08:58 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/IntegerHandler.java
> +    public void setValueByProperty(Property property) {
done

2024-08-15 08:58 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BooleanHandler.java
> +    public void setValueByProperty(Property property) {
done

2024-08-16 16:35 UTC, blcham requested changes
See my last commit, comment or use to refactor rest of the code.

2024-08-18 16:07 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/URLHandler.java
> +    public void setValueByProperty(Property property) {
If I understand correctly, I have tested  the setValueByProperty() for all handlers in commit: `25a84b324f77ce2804b5ce7be30e56141cec7622`

2024-08-18 16:42 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/ListHandler.java
> +    private List<Resource> getResourcesByProperty(Object property) {
I changed the type to RDFNode and removed the handlers from ListHandler. This change will work fine with child classes of RDFNode, but it will not be possible to configure List<Path>, for example. If this is acceptable, please tag me or review my changes. I have tested the new implementation of ListHandler in the test folder.

2024-08-18 16:43 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/Handler.java
> +    protected RDFNode getEffectiveValue(Property property){
It is implemented in commit: `25a84b324f77ce2804b5ce7be30e56141cec7622`

2024-08-18 17:59 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/URLHandler.java
> +                throw new RuntimeException(e);
done

2024-08-19 05:27 UTC, blcham commented
I was not assigned for review so i just assume that it is not finished yet and put you some comments anyway

2024-08-19 14:39 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +            } catch (Exception ex) {
Not sure if you can catch runtime exceptions like NullPointer...

2024-08-19 14:39 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +    abstract T getRDFNodeValue(RDFNode node) throws Exception;
Not sure that I understand rename 
getJavaNativeValue --> getRDFNodeValue

Why generic Exception in the signature?

2024-08-19 14:39 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +     * @throws ScriptRuntimeErrorException If an error occurs during the conversion or setting process.
Duplicate documentation. I do not see the reason to have documentation copied here ... 

Similar comment like:
`@throws ScriptRuntimeErrorException If an error occurs during the conversion or setting process.`

could be copied to the overridden method.

I would write something like ... "in case of error ScriptRuntimeErrorException should be thrown."

2024-08-19 14:39 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +            } catch (Exception ex) {
Why use checked exceptions? And if so, why a generic one?

2024-08-19 14:54 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +    abstract T getRDFNodeValue(RDFNode node) throws Exception;
If I understand correctly, by "JavaNativeValue" you mean basic types (integer, boolean, etc.). I have refactored the handlers, and now this function returns any type based on the value of RDFNode. For example:
```java
@Override
URL getRDFNodeValue(RDFNode node) throws MalformedURLException {
    return new URL(node.toString());
}
```
I will change Exception to IOException. Because for example URLHandler throws MalformedURLException.

2024-08-19 14:58 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +            } catch (Exception ex) {
Some handlers throw IOException. For example URLHandler throws MalformedURLException:

```java
    @Override
    URL getRDFNodeValue(RDFNode node) throws MalformedURLException {
        return new URL(node.toString());
    }
    ```

2024-08-19 15:26 UTC, blcham commented
25a84b324f77ce2804b5ce7be30e56141cec7622

2024-08-19 16:11 UTC, blcham commented on s-pipes-core/src/test/java/cz/cvut/spipes/modules/handlers/ListSetterTest.java
> +class ListSetterTest {
-- It should behave like this:
    - if list exists --> replace its values
    - if list does not exist --> create new list

2024-08-19 16:20 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/Handler.java
> +    protected RDFNode getEffectiveValue(Property property){
getEffectiveValue should be used as follows:

```
if (hasParameterValueAssignment(resource, property)) {
    setter.setValue(getEffectiveValue(rdfNode))  //even if it getEffectiveValue returns null
} 
// do not do anything
```

2024-08-20 13:44 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +     * @throws ScriptRuntimeErrorException If an error occurs during the conversion or setting process.
done

2024-08-20 13:44 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +            } catch (Exception ex) {
done

2024-08-20 13:46 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/AbstractModule.java
> + * output constraints, and handling module-specific configurations.
done

2024-08-20 14:03 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/Handler.java
> +    protected RDFNode getEffectiveValue(Property property){
done

2024-09-11 15:03 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/handlers/BaseRDFNodeHandler.java
> +    abstract T getRDFNodeValue(RDFNode node) throws Exception;
i remember here discussion but not resolution ...

2024-09-11 15:09 UTC, merged