[#228] Implemented processing of xls files without transformation to csv
kbss-cvut/s-pipes pull request #285
Opened 2024-12-12 11:53 UTC by MSattrtand

.xls files are now being processed separately, without conversion to .csv. This is preliminary code, I'll work on reducing the amount of duplicate code using adapters and refractor it.

2024-12-15 20:46 UTC, MSattrtand commented
XLS and CSV files are now processed using adapters, will fix the HTML processing soon

2024-12-15 23:53 UTC, MSattrtand commented
Processing HTML tables works again, though it still has its inelegant solution with a conversion to CSV.

2024-12-18 00:09 UTC, MSattrtand commented
HTML tables are now being processed directly, without conversion. However, I'm not sure that won't introduce more bugs because HTML doesn't store info of all the cells in every row, so I have to use a workaround to remember if we should have merged cells in every place.

2024-12-18 12:40 UTC, blcham requested changes
See my suggestions.

2024-12-18 12:40 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/FileReaderAdapter.java
> +    String getLabel() throws IOException;
? getSheetLabel

2024-12-18 12:40 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +        FileReaderAdapter fileReaderAdapter = new XLSFileReaderAdapter();
File seems strange if we have Stream as input

2024-12-18 12:40 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLSFileReaderAdapter.java
> +    public String[] getHeader() throws IOException {
should support skipHeader = true

2024-12-18 12:40 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLSFileReaderAdapter.java
> +                    if (cellValue != null && cellValue.matches("[-+]?[0-9]*\\,?[0-9]+")) {
cellVaue =  fixNumberFormat(cellValue);

2024-12-18 12:40 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLSFileReaderAdapter.java
> +                    if (cellValue != null && cellValue.matches("[-+]?[0-9]*\\,?[0-9]+")) {
can we find out Workbook.getLocale? if it is too hard make new issue instead

2024-12-18 12:40 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            fileReaderAdapter.initialise(new ByteArrayInputStream(sourceResource.getContent()), sourceResourceFormat, processTableAtIndex);
Before it was implemented like:
```
ICsvListReader listReader = getCsvListReader(csvPreference);

            if (listReader == null) {
                logMissingQuoteError();
                return getExecutionContext(inputModel, outputModel);
            }
```

but there is no reason to have             
```
            if (listReader == null) {
                logMissingQuoteError();
                return getExecutionContext(inputModel, outputModel);
            }
```

outside of getCsvListReader() method.

2024-12-18 12:40 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            tableSchema.adjustProperties(hasInputSchema, outputColumns, sourceResource.getUri());
we lost implementation of `listReader.close()`

2025-01-06 22:28 UTC, blcham requested changes
see my comments

2025-01-07 12:08 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/StreamReaderAdapter.java
> +    static final Logger LOG = LoggerFactory.getLogger(TabularModule.class);
1. Probably not. It's only used in XLS Reader, so I'll move the initialisation of the logger into that class.
2. Yes, it should be StreamReaderAdapter.class or XLSReaderAdapter.class

2025-01-07 12:09 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLSFileReaderAdapter.java
> +    public String[] getHeader() throws IOException {
Done

2025-01-07 12:09 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            fileReaderAdapter.initialise(new ByteArrayInputStream(sourceResource.getContent()), sourceResourceFormat, processTableAtIndex);
Done

2025-01-07 12:09 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            tableSchema.adjustProperties(hasInputSchema, outputColumns, sourceResource.getUri());
Done

2025-01-07 12:09 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +        StreamReaderAdapter streamReaderAdapter = new XLSStreamReaderAdapter();
Done

2025-01-07 12:09 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/StreamReaderAdapter.java
> +    static final Logger LOG = LoggerFactory.getLogger(TabularModule.class);
Done

2025-01-07 17:31 UTC, blcham commented
@MSattrtand please describe this in documentation of the module:

```
SH+ = skipHeader ano 
sH-  = skipHeader ne 
S+ = schema ano
S- = schema ne



- S+SH+
    - not calling getHeader()
    - assume that data looks like in schema    
- S+SH-
    - calling getHeader()
    - adapt schema to match header of the file
        - if ordering is not specified use ordering or the header
        - reuse column IRIs from Schema
- S-SH+
    - not calling getHeader()
    - create column names column_1, column_2, etc.
- S-SH-
    - calling getHeader()
    - create schema entirely based on the header
```

2025-01-08 10:16 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/StreamReaderAdapter.java
> +    void initialise(InputStream inputStream, ResourceFormat sourceResourceFormat, int tableIndex, boolean acceptInvalidQuoting, Charset inputCharset, StreamResource sourceResource) throws IOException
Done

2025-01-08 10:17 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/StreamReaderAdapter.java
> +    boolean hasNextRow() throws IOException;
Done since hasNextRow no longer exists in code

2025-01-08 10:18 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/StreamReaderAdapter.java
> +    String getSheetLabel() throws IOException;
getSheetLabel() - no, the rest - yes, because listreader may throw that exception.

2025-01-08 10:18 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/StreamReaderAdapter.java
> +    String getSheetLabel() throws IOException;
Done

2025-01-08 10:18 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/CSVStreamReaderAdapter.java
> +        //listReader = new CsvListReader(new InputStreamReader(inputStream), csvPreference);
Done

2025-01-08 10:19 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/XLSStreamReaderAdapter.java
> +    public String fixNumberFormat (String cellValue){
Google says that Excel files do not contain information about their decimal separator, so checking every cell is the safest option.

2025-01-08 10:20 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    @Parameter(iri = PARAM_URL_PREFIX + "output-mode", comment = "Output mode. Default is standard-mode('http://onto.fel.cvut.cz/ontologies/lib/module/tabular/standard-mode)")
Done

2025-01-08 10:20 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                streamReaderAdapter = new CSVStreamReaderAdapter(csvPreference);
Done

2025-01-08 10:22 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/CSVStreamReaderAdapter.java
> +        return null;
In the original code, table.setLabel() is never used in the case of CSV files. So, it stays with its default value, which is null

2025-01-08 10:24 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                streamReaderAdapter = new HTMLStreamReaderAdapter();
Actually, it wasn't. table.setLabel() is called later.

`table.setLabel(streamReaderAdapter.getSheetLabel());`

2025-01-08 10:24 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                streamReaderAdapter = new XLSStreamReaderAdapter();
Done

2025-01-08 10:24 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            streamReaderAdapter.initialise(new ByteArrayInputStream(sourceResource.getContent()),
Done

2025-01-08 10:25 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/CSVStreamReaderAdapter.java
> +        listReader = getCsvListReader(csvPreference);
Done

2025-01-08 10:25 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/CSVStreamReaderAdapter.java
> +    public String[] getHeader(Boolean skipHeader) throws IOException {
Done

2025-01-08 10:26 UTC, MSattrtand commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/CSVStreamReaderAdapter.java
> +        return ((listReader.read() != null) || (firstRow != null));
Done, since hasNextRow() was deleted

2025-01-08 12:42 UTC, blcham approved these changes
LGTM

2025-01-08 12:42 UTC, merged