Fix missing handler exceptions
kbss-cvut/s-pipes pull request #287
Opened 2024-12-15 17:02 UTC by kostobog

@blcham @palagdan 
Fixes #286 .

Add CharacterHandler and ModeHandler and register them in HandlerRegistry.

The ModeHandler in `s-pipes-modules-tabular` while HandlerRegistry is in `s-pipes-core`. I had to somehow register the ModeHandler. I choose to add ModuleRegistration and call its register method the static constructors of the two module classes.
Maybe there is a better way to do that?

2024-12-15 21:16 UTC, blcham commented
@kostobog thank you for implementing this fix

2024-12-15 21:41 UTC, blcham commented
@palagdan please revise this PR and if you can fix it by Tuesday, please fix it, otherwise merge this and make new issue.

This issue comes from:
https://github.com/kbss-cvut/s-pipes/pull/276

The problem is that we have loadManualConfiguration function which seems like it is called correcly:
![image](https://github.com/user-attachments/assets/9ce69bc0-b7df-4a9b-9f20-e449e4a924f5)

but we cannot have handler for the Mode.

2024-12-15 21:57 UTC, blcham requested changes
@palagdan please have a look at my comments

2024-12-15 21:57 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ModuleRegistration.java
> +public class ModuleRegistration {
@palagdan  I do not like this for non-reusable param. We should handle it by extending annotation of `@Parameter`.
![image](https://github.com/user-attachments/assets/dc1d67ce-101c-4af9-867d-d5000c80e2eb)

2024-12-15 21:57 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ModuleRegistration.java
> +public class ModuleRegistration {
@palagdan please have a look

2024-12-15 21:57 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/RDF2CSVModule.java
> +    static {ModuleRegistration.register();}
don't like it, see above.

2024-12-15 21:57 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    static {ModuleRegistration.register();}
don't like it, see above.

2024-12-16 11:24 UTC, palagdan commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ModuleRegistration.java
> +public class ModuleRegistration {
@blcham

I have extended the `@Parameter` annotation by adding the handler field.

The documentation has also been updated as well.

2024-12-16 11:25 UTC, palagdan commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +    static {ModuleRegistration.register();}
It was replaced by handler field in an annotation.

2024-12-16 15:01 UTC, blcham requested changes
LGTM, just resolve the provided comments, after that you can Merge (but watch out -- we want to have merge commit as well)

2024-12-16 15:16 UTC, palagdan commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/Parameter.java
> + *       for managing the field's value. If not provided, the {@link Handler} is used by default.</li>
@blcham 

First, I added a DefaultHandler, which does nothing but serves as the default value for the handler field. Later, I decided to use the Handler class itself instead of creating a separate one just for the default value.

In this setup, if the handler is the default class Handler, we use the handler from the type. Otherwise, we use a custom handler. Essentially, we don’t create an instance of the abstract class; it serves purely as a marker.

2024-12-16 15:32 UTC, merged

2024-12-16 22:10 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/modules/Parameter.java
> + *       for managing the field's value. If not provided, the {@link Handler} is used by default.</li>
Ok, Let's talk about this on next meeting. To me this is very confusing ...

To me DefaultHandler seems to have perfect sense ... it is just delegating work to other Handlers using Registry ... So the strange code of type:
```
     if(handlerClazz != Handler.class){
        ...
             else{
                    HandlerRegistry handlerRegistry = HandlerRegistry.getInstance();
                    Handler<?> typeHandler = handlerRegistry.getHandler(f.getType(), resource, executionContext, setter);
                    typeHandler.setValueByProperty(ResourceFactory.createProperty(p.iri()));
```
would not have to exist, because you would treat it as regular handler without need to do `if ... else`