[Feature #21] Implementation of spif:parseDate
kbss-cvut/s-pipes pull request #36
Opened 2022-02-04 12:55 UTC by Matthew-Kulich

Implemented feature #21. 

Take a look at "execReturnsTime_WithoutSeconds" test, which is successful, but there's a warning. It happens when time has no second (e.g. "23:59" ), but it formats correctly to xsd:time.

2022-02-05 12:48 UTC, blcham requested changes
LGTM, there are just 2 minor issues:
- missing javadoc
- not sure if pattern language is optional

I did not put comments to this review response, but to the commit, sorry for that.

2022-02-07 10:46 UTC, Matthew-Kulich commented
"de" stands for Germany.

"If there is "de" and it works ... what is the purpose of having it anyway ?"
- In this state It is useless, but i can think of one usecase which would be useful. It is that user give us pattern or pattern language because thereafter we can decide which pattern it is. [Date formats based on country](https://docs.oracle.com/cd/E19455-01/806-0169/overview-7/index.html)

"could we have test where patternLanguage is null as well ? We should definitely support it."
- Yeah, sure

"missing javadoc"
- I will do it

"Txime ?"
- It is typo i guess but i cant find where it is

"not sure if pattern language is optional"
- i will take a look at it

2022-02-07 17:10 UTC, blcham commented
@Matthew-Kulich you can click to specific comment to see my comments in context (I was confused why you answered me in one message instead of answering me to each separately, and you wrote that you cannot see "Txime"). Have a look here:
![image](https://user-images.githubusercontent.com/3962237/152837199-0ecbfb67-4ee0-4fb4-9c7e-68cd852d0c82.png)

2022-02-07 17:22 UTC, blcham commented
> Implemented feature #21.
> 
> Take a look at "execReturnsTime_WithoutSeconds" test, which is successful, but there's a warning. It happens when time has no second (e.g. "23:59" ), but it formats correctly to xsd:time.

It must be "23:59:00" see:
http://books.xmlschemata.org/relaxng/ch19-77311.html

"
Invalid values include 21:32 (all the parts must be specified), 25:25:10 (the hour part is out of range), -10:00:00 (the hour part is out of range), and 1:20:10 (all the digits must be supplied).
"

2022-02-11 12:29 UTC, blcham requested changes
LGTM, just need modification of message "Some of required parameters were not provided.", as it is not true for all cases when exception is thrown.

Either reformulate it or reimplement as suggested.

2022-02-11 12:29 UTC, blcham commented on s-pipes-core/src/main/java/cz/cvut/spipes/function/spif/ParseDate.java
> +            textValue = text.getLiteralValue().toString();
I think exception "Some of required parameters were not provided." does not make sense for nodes like BNODE or RESOURCE (e.g. \<htttp://example.org/person\> ). 

Just a tip:
I would prefer rather having a function like:
```
textValue = getRequiredParameterLiteralValue(text, 1);
patternValue = getRequiredParameterLiteralValue(pattern, 2);

```

Second parameter is number representing which argument it is (this is rather controversial and can be omited). As such it could generate two kind of error messages:
- "2 argument of this function was is not literal."
- "2 argument of this function is required but missing."

2022-02-11 13:19 UTC, Matthew-Kulich commented on s-pipes-core/src/main/java/cz/cvut/spipes/function/spif/ParseDate.java
> +            textValue = text.getLiteralValue().toString();
Ok, i agree.

2022-02-13 17:07 UTC, blcham approved these changes
LGTM

2022-02-13 22:19 UTC, merged