Feature/validation constraints
kbss-cvut/s-pipes pull request #42
Opened 2022-03-07 09:56 UTC by Matthew-Kulich

2022-03-07 15:25 UTC, blcham requested changes
Please, check my suggestions.

The main issue to me seems to be very artificial example -- or at least it is not very intuitive to understand why somebody would like to create such pipeline (what does it suppose to do?).

2022-03-07 15:25 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation.md
> +There are two types of queries we can validate constraints with:
```suggestion
Each SPipes module can have any number of validation constraints on its input (see `kbss:has-input-graph-constraint`) and its output (see `kbss:has-output-graph-constraint`). Each validation constraint is SPARQL query. Currently, we support 2 types of queries:
```

2022-03-07 15:25 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation.md
> +* `ASK` -- returns true if the condition in the body is met by at least one result set
```suggestion
* `ASK` -- returns true if validation constraint is violated
```

2022-03-07 15:25 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation.md
> +* `ASK` -- returns true if the condition in the body is met by at least one result set
otherwise you are just explaining what is SPARQL ASK query and not how it is relevant to SPipes

2022-03-07 15:25 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation.md
> +* `SELECT` -- returns variable bindings as its result
```suggestion
* `SELECT` -- returns non-empty variable bindings as its result if validation constraint is violated. The variable binding should be used to exemplify/explain what particular entities are violating the constraint.
```

2022-03-07 15:25 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation.md
> +We create simple script which shows the example of constraint validation usage. The script only changes the last name of person and meanwhile validates constraints.
It would be nice to describe the whole story what is pipeline going to do for us and for what we need the validation.

2022-03-07 15:25 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation.md
> +We create simple script which shows the example of constraint validation usage. The script only changes the last name of person and meanwhile validates constraints.
I would start with something like, let's imagine we have pipeline that does ...

2022-03-07 15:25 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation.md
> +                    rdf:id ?id
I would use `:id` instead of all `rdf:id` everywhere, as it is confusing.

rdf:id is not term in rdf vocabulary, there is rdf:ID which is just purely technical element of RDF/XML, i.e. it is not tranformed to equivalent in e.g. turtle format.

2022-03-07 15:25 UTC, blcham commented on doc/examples/hello-world/hello-world.md
> +i.e. root directory of the project [s-pipes-modules](https://kbss.felk.cvut.cz/gitblit/summary/s-pipes-modules.git) (not the directory of this project).
```suggestion
i.e. root directory of the project [s-pipes-modules](https://kbss.felk.cvut.cz/gitblit/summary/s-pipes-modules.git) (Note! : it is different project not a sub-directory of this project).
```

2022-03-20 08:57 UTC, blcham commented
No closing yet, still need to work on this, but I experienced this while trying #57.

2022-03-24 00:54 UTC, blcham commented
still not finished.

2022-03-24 09:13 UTC, blcham commented
Done, @Matthew-Kulich please check.

2022-03-24 09:25 UTC, Matthew-Kulich reviewed
LGTM,  but please decide about the illustrative picture

2022-03-24 09:25 UTC, Matthew-Kulich commented on doc/examples/constraint-validation/constraint-validation-graphical-notion.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Does not correspond to changed example. I can create new one or we can delete it.

2022-03-24 09:26 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation-graphical-notion.svg
> +<?xml version="1.0" encoding="UTF-8"?>
@Matthew-Kulich It would be great if you could provide new one

2022-03-24 09:27 UTC, blcham commented on doc/examples/constraint-validation/constraint-validation-graphical-notion.svg
> +<?xml version="1.0" encoding="UTF-8"?>
I forgot about it as it was not referenced in the text. Moreover I was not able to modify because you did not include source file in there.

2022-03-24 10:09 UTC, merged