[Feature #18] Add swagger to document REST API
kbss-cvut/s-pipes pull request #52
Opened 2022-03-16 12:07 UTC by Matthew-Kulich

2022-03-16 12:54 UTC, blcham requested changes
LGTM, just issue with API version, see my comments

2022-03-16 12:54 UTC, blcham commented on s-pipes-web/src/main/java/cz/cvut/spipes/config/SpringFoxConfig.java
> +                .version("v0.3.0")
IMO, It is not a good idea to hardcode the version. 

If you want, you can set this up by configuration similarly as done here: https://github.com/opendata-mvcr/sgov/blob/3e27c6d0ad188cf086d3be1d620802c04b51938f/src/main/java/com/github/sgov/server/config/SpringFoxConfig.java

Another option is just removing this line and having no version there.

2022-03-18 09:01 UTC, Matthew-Kulich commented on s-pipes-web/src/main/java/cz/cvut/spipes/config/SpringFoxConfig.java
> +                .version("v0.3.0")
For now I will delete that and later when we will migrate to spring boot I will add it.

2022-03-18 09:10 UTC, blcham approved these changes
LGTM

2022-03-18 09:11 UTC, merged