Feature/csv no header
kbss-cvut/s-pipes pull request #91
Opened 2022-07-26 07:24 UTC by Matthew-Kulich

2022-07-28 07:34 UTC, blcham requested changes

2022-07-28 07:34 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +    public void executeSimpleTransformationWithoutHeaders() throws URISyntaxException, IOException {
i mean something like "$Preconditions_$whatItShouldReturn"

2022-08-01 11:00 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +    public void executeSimpleTransformationWithoutHeaders() throws URISyntaxException, IOException {
I'm not sure, I took over the name convention from the tests from Zdenek. But of course I can name it like that

2022-08-01 11:01 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                                logError("Invalid URI: " + rdfNode);
Does blank node work with JOPA?

2022-08-01 11:01 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +            if(skipHeader){
Agree

2022-08-03 08:42 UTC, blcham requested changes
I put quite many comments, if it is too hard to follow we can have online meeting instead.

2022-08-03 08:42 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/examples/01/input-data-schema.ttl
> -    csvw:name "Employee_No" ;
@Matthew-Kulich I believe that we did not understand each other here. I believe that this file was correctly written. I believe the following is true:
- `csvw:property` does not exists in specification but I am ok to use it here. (**thoughts for future**: I believe that it would be best not even use `csvw-e:property`, but have own url e.g. "https://onto.fel.cvut.cz/csvw/"
- since csvw:property does not exists so we need to have always some kind of ID here. I guess csvw:name stands for that. Moreover csvw:title is human readable property so this is where i would expect to have " " (space) e.g. "Employee No"



-----

See: https://www.w3.org/ns/csvw

**title**
For a Transformation A natural language property that describes the format that will be generated from the transformation. For a Column: A natural language property that provides possible alternative names for the column.

-----

**name**
An atomic property that gives a single canonical name for the column. The value of this property becomes the name annotation for the described column.

2022-08-03 08:42 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/examples/noHeader/schemaExample/input-data-schema.ttl
> -    csvw:title "col_2";
:+1: 
I agree to remove this.

2022-08-03 08:42 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +    @ValueSource(strings = {"moreColumns", "lessColumns", "noColumns"})
:+1 good you tried parametrized tests

2022-08-03 08:45 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                                logError("Invalid URI: " + rdfNode);
No, JOPA does not support blank nodes yet, but the specification is talking about blank nodes ... 

so we can output **non-blank** nodes, but must be able to read blank nodes.

2022-08-03 08:47 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +     void executeTabularModule_withDataSchemaNoHeader_returnsNamedColumnsFromSchema()
Maybe I would even "executeSelf_withDataSchemaNoHeader" --> "executeSelfwithDataSchemaNoHeader" ... but i don't see it as very important as soon as we are consistent across all tests

2022-08-03 10:32 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +     void executeTabularModule_withDataSchemaNoHeader_returnsNamedColumnsFromSchema()
Ok, It seems that we are not using underscores.

2022-08-08 10:24 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/test/resources/examples/01/input-data-schema.ttl
> -    csvw:name "Employee_No" ;
Done

2022-08-08 10:32 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java
> +                                logError("Invalid URI: " + rdfNode);
This part is used only for ordering nodes but we can discuss this on standup to synchronize

2022-08-25 13:39 UTC, merged