Feature/support bnodes
kbss-cvut/s-pipes pull request #93
Opened 2022-08-25 09:19 UTC by Matthew-Kulich

Merging this PR to csv-no-header branch, because after merge I will have to adjust tests to correspond to now feature.

2022-08-29 09:57 UTC, blcham approved these changes

2022-08-29 09:58 UTC, blcham requested changes
Not reviewed yet.

2022-08-29 10:18 UTC, blcham requested changes

2022-08-29 10:18 UTC, blcham commented on s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/util/BNodesTransformer.java
> +    public static Model convertBNodesToNonBNodes(Model model) {
? static ?

IMHO, this won't work if the pipeline would have Tabular module called twice or if you execute the pipeline twice in parallel. What do u think?

I guess you need to call something like:
b = new BNodesTransormer;
b.convertBNodesToNonBNodes()

2022-08-29 10:18 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/examples/lessColumns/input-data-schema.ttl
> +    csvw:propertyUrl :bookingno_i ;
IMO, this is not correct according to specification. If I remember correctly range of propertyUrl is Literal.

On the other hand, we wanted to define something like `csvw-e:property` that would link to Resource,

2022-08-29 10:18 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/examples/lessColumns/input-data-schema.ttl
> +    csvw:propertyUrl :bookingno_i ;
But we already discussed it  ...

Here are some fragments from documentation:

```
uriTemplate dfs:subClassOf xsd:string
```
```
propertyUrl
csvw:propertyUrl with string values interpreted as csvw:uriTemplate
````

2022-08-29 10:18 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/examples/withProperty/expected-output.ttl
> +                              "http://onto.fel.cvut.cz/data/#row-{_row}" ;
Don't understand why we removed this.

2022-08-29 10:18 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/examples/withProperty/expected-output.ttl
> +                <http://onto.fel.cvut.cz/data/user_sign_p>  ;
see comment above?

2022-08-29 10:18 UTC, blcham commented on s-pipes-modules/module-tabular/src/test/resources/examples/withProperty/expected-output.ttl
> +                <http://onto.fel.cvut.cz/data/Start_Date_p>  ;
there are many issues like this one .... this is not correct

2022-08-29 10:45 UTC, blcham commented
csvw:propertyUrl -- semantika je definovana, nesmime predefinovat, xsd:range je xsd:string. Kdykoli generujeme (na vystupe) schemu musi byt csvw:propertyUrl pouzita. Na vstupe muze byt i jenom "csvw-e:property".
csvw-e:property -- todle si definujem sami a xsd:range je rdf:Resource

2022-08-29 16:20 UTC, blcham approved these changes
You got me here!

2022-08-29 18:17 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/test/resources/examples/withProperty/expected-output.ttl
> +                              "http://onto.fel.cvut.cz/data/#row-{_row}" ;
Implemented

2022-08-29 18:17 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/test/resources/examples/withProperty/expected-output.ttl
> +                <http://onto.fel.cvut.cz/data/Start_Date_p>  ;
Done

2022-08-29 18:18 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/test/resources/countries-model-output.ttl
> +                              "http://test-file#row-{_row}" ;
Ok, the used version is 0.18.2

2022-08-30 13:33 UTC, blcham requested changes
LGTM, can be merged but after tests are not failing.

2022-08-30 18:55 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +        for (int i = 2; i <= 4; i++) {
It is the number of rows. The first one looks like `<http://onto.fel.cvut.cz/data/#row-2>`

2022-08-30 18:55 UTC, Matthew-Kulich commented on s-pipes-modules/module-tabular/src/test/java/cz/cvut/spipes/modules/TabularModuleTest.java
> +    void assertIsomorphic(Model actualModel, Model expectedModel){
Ok

2022-08-30 18:59 UTC, Matthew-Kulich commented
@blcham I found the issue, look at the last commit, there was a bad prefix for `kbss-csvw`

2022-08-31 04:22 UTC, blcham approved these changes
LGTM

2022-08-31 07:39 UTC, merged